# The config recipe.
recipe: default.v1

# The assistant project unique identifier
# This default value must be replaced with a unique assistant name within your deployment
assistant_id: 20250831-023742-shiny-volume

language: en
pipeline:
# - name: WhitespaceTokenizer
# - name: CountVectorsFeaturizer
# - name: LogisticRegressionClassifier
# - name: RegexEntityExtractor
# - name: DIETClassifier
# - name: EntitySynonymMapper
# - name: NLUCommandAdapter
- name: CompactLLMCommandGenerator
  llm:
    model_group: genai_llm
  flow_retrieval:
    active: false

# Configuration for Rasa Core.
policies:
- name: FlowPolicy
# - name: MemoizationPolicy
# - name: RulePolicy
# - name: IntentlessPolicy
